[env:esp32-c3-devkitm-1]
platform = espressif32@6.5.0
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.flash_mode = dio
lib_deps = 
    tzapu/WiFiManager @ ^2.0.17
    bblanchon/ArduinoJson @ ^6.21.5
